config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get "features" => "pages#features"
  get "contact" => "pages#contact"
  get "ebook" => "pages#ebook"

  resources :contacts, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < MailForm::Base
	attribute :name,      	:validate => true
	attribute :email,     	:validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
	attribute :message,		:validate => true
	attribute :nickname,  	:captcha  => true

	def headers
	    {
	      :subject => "Backbone Contact Form",
	      :to => "anthony@anthonyfrancis.co",
	      :from => %("#{name}" <#{email}>)
	    }
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

def new
	@contact = Contact.new
end

def create
	@contact = Contact.new(params[:contact])
	@contact.request = request
	if @contact.deliver
		flash.now[:error] = nil
	else
		flash.now[:error] = 'Cannot send message'
		render :new
	end
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def features
  end

  def contact
  end

  def ebook
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contacts/create.html.erb
Hello

app/views/contacts/new.html.erb
<div class="bloc bloc-fill-screen bg-ebook-20image l-bloc" id="bloc-0">
	<div class="container fill-bloc-top-edge">
		<div class="row">
			<div class="col-12">
				<nav class="navbar navbar-light row navbar-expand-md">
					<a class="navbar-brand " href="/">

						<%= image_tag("Logo.png", :size => "150x50") %>
						</a>
					<button id="nav-toggle" type="button" class="ui-navbar-toggler navbar-toggler border-0 p-0 mr-md-0 ml-auto" data-toggle="collapse" data-target=".navbar-1" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse navbar-1">
						<ul class="site-navigation nav navbar-nav ml-auto colour-nav">
							<li class="nav-item">
								<%= link_to "Home", root_path %>
							</li>
							<li class="nav-item">
								<%# link_to "Feature", features_path %>
							</li>
							<li class="nav-item">
								<a href="https://www.amazon.co.uk/dp/B07KSNDXGT">Buy Now</a>
							</li>
							<li class="nav-item">
								<%= link_to "Contact", contact_path %>
							</li>
						</ul>
					</div>
				</nav>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-lg-6 offset-lg-3">
				<h1 class="mg-md colour text-center">
					Contact our team
				</h1>
				<h4 class="mg-md colour text-center">
					Still have questions? You are more than welcomed to contact us and we will be in touch with you shortly. 
				</h4>			
			</div>
		</div>
	</div>
</div>
<div class="container fill-bloc-bottom-edge">
		<div class="row">
			<div class="col-12">
				<div class="text-center">
					<a href="#" data-scroll-speed="1000" onclick="scrollToTarget('0',this)"><span class="fa fa-angle-down icon-md animated bounce animDelay08"></span></a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-0 END -->

<!-- bloc-1 -->
<div class="bloc l-bloc " id="bloc-1">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-lg-6 offset-lg-3 offset-md-2 col-md-8">
				<form id="form_29838" novalidate>
					<%= form_for @contact do |f| %>
						<%= f.label :name %>
						<%= f.text_field :name, class: "form-control", required: true %>

						<br>

						<%= f.label :email %>
						<%= f.email_field :email, class: "form-control", required: true %>

						<br>

						<%= f.label :message %>
						<%= f.text_area :message, class: "form-control", as: :text %>

						<div class="hidden">
							<%= f.label :nickname %>
							<%= f.text_field :nickname, hint: 'leave this field blank' %>
						</div>

						<%= f.submit 'Send Message', class: "bloc-button btn btn-d btn-lg btn-block" %>
					<% end %>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- bloc-1 END -->

<!-- bloc-4 -->
<div class="bloc bgc-black d-bloc " id="bloc-4">
	<div class="container bloc-lg">
		<div class="row">
		
		</div>
	</div>
</div>
<!-- bloc-4 END -->

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Backbone", root_path, class: "navbar-brand" %>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Posture Corrector", features_path %></li>
      <li><a href="https://www.amazon.co.uk/dp/B07KSNDXGT">Buy Now</a></li>
      <li><%= link_to "Contact", contact_path %></li> 
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Backbone – Better Posture Better Life</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel='stylesheet' id='sd-fonts-css'  href='http://fonts.googleapis.com/css?family=Lato:400,300,700&subset=latin,latin-ext&ver=1.0.0' type='text/css' media='all' />
  </head>

  <body>
    <%# render 'layouts/header' %>
   
      <%= yield %>

  </body>
</html>

app/views/pages/contact.html.erb
<div class="bloc bloc-fill-screen bg-ebook-20image l-bloc" id="bloc-0">
	<div class="container fill-bloc-top-edge">
		<div class="row">
			<div class="col-12">
				<nav class="navbar navbar-light row navbar-expand-md">
					<a class="navbar-brand " href="/">

						<%= image_tag("Logo.png", :size => "150x50") %>
						</a>
					<button id="nav-toggle" type="button" class="ui-navbar-toggler navbar-toggler border-0 p-0 mr-md-0 ml-auto" data-toggle="collapse" data-target=".navbar-1" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse navbar-1">
						<ul class="site-navigation nav navbar-nav ml-auto colour-nav">
							<li class="nav-item">
								<%= link_to "Home", root_path %>
							</li>
							<li class="nav-item">
								<%# link_to "Feature", features_path %>
							</li>
							<li class="nav-item">
								<a href="https://www.amazon.co.uk/dp/B07KSNDXGT">Buy Now</a>
							</li>
							<li class="nav-item">
								<%= link_to "Contact", contact_path %>
							</li>
						</ul>
					</div>
				</nav>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-lg-6 offset-lg-3">
				<h1 class="mg-md colour text-center">
					Contact our team
				</h1>
				<h4 class="mg-md colour text-center">
					Still have questions? You are more than welcomed to contact us and we will be in touch with you shortly. 
				</h4>			
			</div>
		</div>
	</div>
</div>
<div class="container fill-bloc-bottom-edge">
		<div class="row">
			<div class="col-12">
				<div class="text-center">
					<a href="#" data-scroll-speed="1000" onclick="scrollToTarget('0',this)"><span class="fa fa-angle-down icon-md animated bounce animDelay08"></span></a>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- bloc-0 END -->

<!-- bloc-1 -->
<div class="bloc l-bloc " id="bloc-1">
	<div class="container bloc-lg">
		<div class="row">
			<div class="col-lg-6 offset-lg-3 offset-md-2 col-md-8">
				<form id="form_29838" novalidate>
					<div class="form-group">
						<label>
							Name
						</label>
						<input id="name_29838" class="form-control" required />
					</div>
					<div class="form-group">
						<label>
							Email
						</label>
						<input id="email_29838" class="form-control" type="email" required />
					</div>
					<div class="form-group">
						<label>
							Message
						</label><textarea id="message_29838" class="form-control" rows="4" cols="50" required></textarea>
					</div>
					<div class="form-check">
						<input class="form-check-input" type="checkbox" id="optin_29838" data-validation-minchecked-message="You must agree to this before we can take your information." data-validation-minchecked-minchecked="1" name="optin" />
						<label class="form-check-label">
							We can send you product updates and offers via email. It is possible to opt-out at any time.
						</label>
					</div> 
					<button class="bloc-button btn btn-d btn-lg btn-block" type="submit">
						Submit
					</button>
				</form>
			</div>
		</div>
	</div>
</div>
<!-- bloc-1 END -->

<!-- bloc-4 -->
<div class="bloc bgc-black d-bloc " id="bloc-4">
	<div class="container bloc-lg">
		<div class="row">
		
		</div>
	</div>
</div>
<!-- bloc-4 END -->

app/views/pages/ebook.html.erb
<div class="bloc bloc-fill-screen bg-ebook-20image l-bloc" id="bloc-0">
	<div class="container fill-bloc-top-edge">
		<div class="row">
			<div class="col-12">
				<nav class="navbar navbar-light row navbar-expand-md">
					<a class="navbar-brand " href="/">

						<%= image_tag("Logo.png", :size => "150x50") %>
						</a>
					<button id="nav-toggle" type="button" class="ui-navbar-toggler navbar-toggler border-0 p-0 mr-md-0 ml-auto" data-toggle="collapse" data-target=".navbar-1" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse navbar-1">
						<ul class="site-navigation nav navbar-nav ml-auto colour-nav">
							<li class="nav-item">
								<%= link_to "Home", root_path %>
							</li>
							<li class="nav-item">
								<%# link_to "Feature", features_path %>
							</li>
							<li class="nav-item">
								<a href="https://www.amazon.co.uk/dp/B07KSNDXGT">Buy Now</a>
							</li>
							<li class="nav-item">
								<%= link_to "Contact", contact_path %>
							</li>
						</ul>
					</div>
				</nav>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-lg-6 offset-lg-1">
				<h1 class="mg-md colour">
					Work towards a better <br> posture and better life
				</h1>
				<h4 class="mg-md colour">
					In this eBook you will find exercises with the resistance band, an office workout and tips and tricks to improve your posture. We do care about you with this book you get all the information to improve your posture as quick as possible.
				</h4>			
			</div>
			<div class="col-lg-3">
				<%= image_tag("cover.png", :width => "400", :height => "auto") %>
			</div>
		</div>
	</div>

	<div class="row">
		<div id="" class="col-lg-6 offset-lg-1">
				<form action="https://shop.us19.list-manage.com/subscribe/post?u=dbbf205b650ddd3ce89367568&amp;id=80a0c1c1c2" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
				<div  class="form-group">
					<p class="colour">Subscribe to our mailing list and get your free eBook</p>
				<div class="mc-field-group">
					<input type="email" value="" name="EMAIL" class="required email form-control" id="mce-EMAIL" placeholder="Email Address">
				</div>
					<div id="mce-responses" class="clear">
						<div class="response" id="mce-error-response" style="display:none"></div>
						<div class="response" id="mce-success-response" style="display:none"></div>
					</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
				    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_dbbf205b650ddd3ce89367568_80a0c1c1c2" tabindex="-1" value=""></div>
				    <br>
				    <div class="clear"><input type="submit" value="GET YOUR EBOOK" name="subscribe" class="btn btn-primary"></div>
				    </div>
				</form>
			</div>
	</div>
	<div class="container fill-bloc-bottom-edge">
		<div class="row">
			<div class="col-12">
				<div class="text-center">
					<a href="#" data-scroll-speed="1000" onclick="scrollToTarget('0',this)"><span class="fa fa-angle-down icon-md animated bounce animDelay08"></span></a>
				</div>
			</div>
		</div>
	</div>
</div>



<!-- Begin Mailchimp Signup Form -->
<link href="//cdn-images.mailchimp.com/embedcode/classic-10_7.css" rel="stylesheet" type="text/css">
<style type="text/css">
	#mc_embed_signup{clear:left; font:14px Helvetica,Arial,sans-serif; }
	/* Add your own Mailchimp form style overrides in your site stylesheet or in this style block.
	   We recommend moving this block and the preceding CSS link to the HEAD of your HTML file. */
</style>

<!-- <script type='text/javascript' src='//s3.amazonaws.com/downloads.mailchimp.com/js/mc-validate.js'></script><script type='text/javascript'>(function($) {window.fnames = new Array(); window.ftypes = new Array();fnames[0]='EMAIL';ftypes[0]='email';fnames[1]='FNAME';ftypes[1]='text';fnames[3]='ADDRESS';ftypes[3]='address';fnames[4]='PHONE';ftypes[4]='phone';fnames[5]='BIRTHDAY';ftypes[5]='birthday';}(jQuery));var $mcj = jQuery.noConflict(true);</script> -->
<!--End mc_embed_signup-->

app/views/pages/features.html.erb
features.html.erb

app/views/pages/home.html.erb
<div class="bloc bloc-fill-screen bg-ebook-20image l-bloc" id="bloc-0">
	<div class="container fill-bloc-top-edge">
		<div class="row">
			<div class="col-12">
				<nav class="navbar navbar-light row navbar-expand-md">
					<a class="navbar-brand " href="/">

						<%= image_tag("Logo.png", :size => "150x50") %>
						</a>
					<button id="nav-toggle" type="button" class="ui-navbar-toggler navbar-toggler border-0 p-0 mr-md-0 ml-auto" data-toggle="collapse" data-target=".navbar-1" aria-expanded="false" aria-label="Toggle navigation">
						<span class="navbar-toggler-icon"></span>
					</button>
					<div class="collapse navbar-collapse navbar-1">
						<ul class="site-navigation nav navbar-nav ml-auto colour-nav">
							<li class="nav-item">
								<%= link_to "Home", root_path %>
							</li>
							<li class="nav-item">
								<%# link_to "Feature", features_path %>
							</li>
							<li class="nav-item">
								<a href="https://www.amazon.co.uk/dp/B07KSNDXGT">Buy Now</a>
							</li>
							<li class="nav-item">
								<%= link_to "Contact", contact_path %>
							</li>
						</ul>
					</div>
				</nav>
			</div>
		</div>
	</div>
	<div class="container">
		<div class="row">
			<div class="col-lg-12 hero-first-col-mb">
				<h1 class="mg-md text-center h1-style colour">
					Better Posture <br>Better Life
				</h1>
				<h3 class="mg-md float-none text-center colour">
					In these days we use computers, laptops and our phones what can cause a bad posture by slouching over them. Do something about this now!
				</h3>
				<div class="text-center">
				</div>
			</div>
		</div>
	</div>
	<div class="container fill-bloc-bottom-edge">
		<div class="row">
			<div class="col-12">
				<div class="text-center">
					<a href="#" data-scroll-speed="1000" onclick="scrollToTarget('0',this)"><span class="fa fa-angle-down icon-md animated bounce animDelay08"></span></a>
				</div>
			</div>
		</div>
	</div>
</div>